apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-exporter
  template:
    metadata:
      labels:
        app: prometheus-exporter
    spec:
      containers:
      - name: prometheus-exporter
        image: btc_exporter
        ports:
        - containerPort: 8000
        imagePullPolicy: Never
